const ALPHABET = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L",
    "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z",
    "1", "2", "3", "4", "5", "6", "7", "8", "9"];

const COUNTRIES = {
    "AR": "Argentina",
    // "AM": "Armenia",
    "AU": "Australia",
    "AT": "Austria",
    "AZ": "Azerbaijan",
    "BD": "Bangladesh",
    "BY": "Belarus",
    "BE": "Belgium",
    // "BZ": "Belize",
    "BR": "Brazil",
    "BG": "Bulgaria",
    "CA": "Canada",
    // "CF": "Central African Republic",
    // "CL": "Chile",
    "CN": "China",
    // "CO": "Colombia",
    // "CU": "Cuba",
    // "CY": "Cyprus",
    "CZ": "Czechia",
    "DK": "Denmark",
    "EG": "Egypt",
    "EE": "Estonia",
    "FI": "Finland",
    "FR": "France",
    // "GE": "Georgia",
    "DE": "Germany",
    "GR": "Greece",
    "HK": "Hong Kong",
    "HU": "Hungary",
    "IN": "India",
    "ID": "Indonesia",
    // "IL": "Israel",
    "IT": "Italy",
    "JP": "Japan",
    // "KZ": "Kazakhstan",
    // "KE": "Kenya",
    // "KP": "North Korea",
    "KR": "South Korea",
    // "KW": "Kuwait",
    // "KG": "Kyrgyzstan",
    "LV": "Latvia",
    // "LB": "Lebanon",
    // "LS": "Lesotho",
    // "LR": "Liberia",
    // "LY": "Libya",
    "LI": "Liechtenstein",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    // "MK": "Macedonia (the former Yugoslav Republic of)",
    "MY": "Malaysia",
    // "MX": "Mexico",
    // "MD": "Moldova",
    // "MC": "Monaco",
    // "MN": "Mongolia",
    // "MA": "Morocco",
    // "MZ": "Mozambique",
    // "NP": "Nepal",
    "NL": "Netherlands",
    "NZ": "New Zealand",
    // "NI": "Nicaragua",
    "NO": "Norway",
    // "PK": "Pakistan",
    // "PE": "Peru",
    "PH": "Philippines",
    "PL": "Poland",
    "PT": "Portugal",
    "RO": "Romania",
    "RU": "Russian Federation",
    // "SA": "Saudi Arabia",
    // "RS": "Serbia",
    "SG": "Singapore",
    "SK": "Slovakia",
    "SI": "Slovenia",
    // "SO": "Somalia",
    "ZA": "South Africa",
    "ES": "Spain",
    "LK": "Sri Lanka",
    "SD": "Sudan",
    // "SZ": "Swaziland",
    "SE": "Sweden",
    "CH": "Switzerland",
    // "SY": "Syrian Arab Republic",
    "TW": "Taiwan",
    // "TJ": "Tajikistan",
    "TH": "Thailand",
    // "TN": "Tunisia",
    "TR": "Turkey",
    "TM": "Turkmenistan",
    "UA": "Ukraine",
    "AE": "United Arab Emirates",
    "GB": "Great Britain",
    "US": "United States of America",
    "UZ": "Uzbekistan",
    "VE": "Venezuela",
    "VN": "Viet Nam"
};

const ENGINE_TYPES = {
    1: 'benzine',
    2: 'diesel',
    3: 'gas-benzine',
    4: 'electric',
    5: 'hybrid'
};

const GEAR_TYPES = {
    1: 'manual',
    2: 'automatic',
    3: 'semi-automatic',
    4: 'CVT'
};

export {
    ALPHABET, COUNTRIES, ENGINE_TYPES, GEAR_TYPES
}
