# Generated by Django 2.0.6 on 2018-07-15 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PartsFB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parttype',
            name='category',
            field=models.CharField(choices=[('EN', 'Engine'), ('EL', 'Electrical system'), ('TR', 'Power transmission'), ('BR', 'Brakes'), ('SW', 'Springs and wheels'), ('BI', 'Body and interior'), ('OT', 'Other')], max_length=2),
        ),
    ]
