# Generated by Django 2.0.6 on 2018-07-15 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PartsFB', '0002_auto_20180715_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='description',
        ),
    ]
