# Generated by Django 2.0.6 on 2018-07-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartsFB', '0004_auto_20180715_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='manufacture_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_style',
            field=models.IntegerField(blank=True, choices=[(1, 'Sedan'), (2, 'Coupe'), (3, 'Wagon'), (4, 'Minivan'), (5, 'SUV/Crossover'), (6, 'Convertible'), (7, 'Hatchback'), (8, 'Van')], null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_type',
            field=models.IntegerField(blank=True, choices=[(1, 'benzine'), (2, 'diesel'), (3, 'gas-benzine'), (4, 'electric'), (5, 'hybrid')], null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_volume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='gear',
            field=models.IntegerField(blank=True, choices=[(1, 'manual'), (2, 'automatic'), (3, 'semi-automatic'), (4, 'CVT')], null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='stars',
            field=models.IntegerField(choices=[(1, 'bad'), (2, 'no bad'), (3, 'normal'), (4, 'good'), (5, 'very good')]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='parttype',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
