# https://github.com/SmileyChris/django-countries/blob/master/django_countries/data.py
from django.utils.translation import ugettext_lazy as _


COUNTRIES = (
    ("AR", _("Argentina")),
    # ("AM", _("Armenia")),
    ("AU", _("Australia")),
    ("AT", _("Austria")),
    ("AZ", _("Azerbaijan")),
    ("BD", _("Bangladesh")),
    ("BY", _("Belarus")),
    ("BE", _("Belgium")),
    # ("BZ", _("Belize")),
    ("BR", _("Brazil")),
    ("BG", _("Bulgaria")),
    ("CA", _("Canada")),
    # ("CF", _("Central African Republic")),
    # ("CL", _("Chile")),
    ("CN", _("China")),
    # ("CO", _("Colombia")),
    # ("CU", _("Cuba")),
    # ("CY", _("Cyprus")),
    ("CZ", _("Czechia")),
    ("DK", _("Denmark")),
    ("EG", _("Egypt")),
    ("EE", _("Estonia")),
    ("FI", _("Finland")),
    ("FR", _("France")),
    # ("GE", _("Georgia")),
    ("DE", _("Germany")),
    ("GR", _("Greece")),
    ("HK", _("Hong Kong")),
    ("HU", _("Hungary")),
    ("IN", _("India")),
    ("ID", _("Indonesia")),
    # ("IL", _("Israel")),
    ("IT", _("Italy")),
    ("JP", _("Japan")),
    # ("KZ", _("Kazakhstan")),
    # ("KE", _("Kenya")),
    # ("KP", _("North Korea")),
    ("KR", _("South Korea")),
    # ("KW", _("Kuwait")),
    # ("KG", _("Kyrgyzstan")),
    ("LV", _("Latvia")),
    # ("LB", _("Lebanon")),
    # ("LS", _("Lesotho")),
    # ("LR", _("Liberia")),
    # ("LY", _("Libya")),
    ("LI", _("Liechtenstein")),
    ("LT", _("Lithuania")),
    ("LU", _("Luxembourg")),
    # ("MK", _("Macedonia (the former Yugoslav Republic of)")),
    ("MY", _("Malaysia")),
    # ("MX", _("Mexico")),
    # ("MD", _("Moldova (the Republic of)")),
    # ("MC", _("Monaco")),
    # ("MN", _("Mongolia")),
    # ("MA", _("Morocco")),
    # ("MZ", _("Mozambique")),
    # ("NP", _("Nepal")),
    ("NL", _("Netherlands")),
    ("NZ", _("New Zealand")),
    # ("NI", _("Nicaragua")),
    ("NO", _("Norway")),
    # ("PK", _("Pakistan")),
    # ("PE", _("Peru")),
    ("PH", _("Philippines")),
    ("PL", _("Poland")),
    ("PT", _("Portugal")),
    ("RO", _("Romania")),
    ("RU", _("Russian Federation")),
    # ("SA", _("Saudi Arabia")),
    # ("RS", _("Serbia")),
    ("SG", _("Singapore")),
    ("SK", _("Slovakia")),
    ("SI", _("Slovenia")),
    # ("SO": _("Somalia")),
    ("ZA", _("South Africa")),
    ("ES", _("Spain")),
    ("LK", _("Sri Lanka")),
    ("SD", _("Sudan")),
    # ("SZ", _("Swaziland")),
    ("SE", _("Sweden")),
    ("CH", _("Switzerland")),
    # ("SY", _("Syrian Arab Republic")),
    ("TW", _("Taiwan (Province of China)")),
    # ("TJ", _("Tajikistan")),
    ("TH", _("Thailand")),
    # ("TN", _("Tunisia")),
    ("TR", _("Turkey")),
    ("TM", _("Turkmenistan")),
    ("UA", _("Ukraine")),
    ("AE", _("United Arab Emirates")),
    ("GB", _("United Kingdom")),
    ("US", _("United States of America")),
    ("UZ", _("Uzbekistan")),
    ("VE", _("Venezuela")),
    ("VN", _("Viet Nam")),
)

ENGINE_TYPE = (
    (1, 'petrol'),
    (2, 'diesel'),
    (3, 'electric'),
    (4, 'hybrid'),
    # (3, 'gas-benzine')
)

GEAR_TYPE = (
    (1, 'manual'),
    (2, 'automatic'),
    (3, 'semi-automatic'),
    (4, 'CVT')
)

BODY_STYLE = (
    (1, 'Sedan'),
    (2, 'Coupe'),
    (3, 'Wagon'),
    (4, 'Minivan'),
    (5, 'SUV/Crossover'),
    (6, 'Convertible'),
    (7, 'Hatchback'),
    (8, 'Van')
)

PART_CATEGORIES = (
    ("EN", _("Engine")),
    ("FI", _("Filters")),
    ("CO", _("Cooling System")),
    ("EX", _("Exhaust System")),
    ("SS", _("Suspension and steering")),
    ("BR", _("Brake System")),
    ("EL", _("Electrics")),
    ("FU", _("Fuel system")),
    ("HE", _("Heater")),
    ("TR", _("Transmission and gearing")),
    ("LI", _("Lighting")),
    ("BI", _("Body and interior")),
    ("OT", _("Other")),
    # "BA": _("Batteries"),
    # "OF": _("Oils and fluids"),
    # "AE": _("Accessories and equipment"),
)

# For generating an anonymous user
FIRST_NAMES = {"Anonymous"}
LAST_NAMES = {"User"}

